import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, PieChart, Pie, Cell } from 'recharts';
import { LayoutDashboard, ArrowLeftRight, ChartNoAxesCombined, Wallet, Settings, Search, Bell, Plus, ArrowUpRight, ArrowDownRight, Download, ChevronDown, MoreHorizontal, CalendarDays, SlidersHorizontal, X, Menu, Sun, Moon, Trash2, Pencil, Check, Sparkles, CircleHelp, LogOut } from 'lucide-react';
import './style.css';

const seed=[
 {id:1,name:'Whole Foods Market',category:'Groceries',date:'2025-06-24',amount:-84.32,type:'Expense',icon:'W',color:'#f5e9dc'},
 {id:2,name:'Acme Studio',category:'Salary',date:'2025-06-23',amount:4250,type:'Income',icon:'A',color:'#e8e5ff'},
 {id:3,name:'Uber',category:'Transport',date:'2025-06-22',amount:-18.50,type:'Expense',icon:'U',color:'#eeeeee'},
 {id:4,name:'Netflix',category:'Entertainment',date:'2025-06-21',amount:-15.99,type:'Expense',icon:'N',color:'#ffe6e5'},
 {id:5,name:'Blue Bottle Coffee',category:'Food & Drink',date:'2025-06-20',amount:-8.75,type:'Expense',icon:'B',color:'#e3f0e9'},
 {id:6,name:'Airbnb',category:'Travel',date:'2025-06-18',amount:-246,type:'Expense',icon:'A',color:'#ffe3e8'},
 {id:7,name:'Figma',category:'Software',date:'2025-06-17',amount:-24,type:'Expense',icon:'F',color:'#f5e2ed'},
 {id:8,name:'Freelance project',category:'Side income',date:'2025-06-15',amount:680,type:'Income',icon:'↗',color:'#e3f0e9'},
 {id:9,name:'Trader Joe’s',category:'Groceries',date:'2025-06-14',amount:-62.40,type:'Expense',icon:'T',color:'#e6efff'},
 {id:10,name:'Spotify',category:'Entertainment',date:'2025-06-12',amount:-10.99,type:'Expense',icon:'S',color:'#dcf3e5'}
];
const trend=[{month:'Jan',in:4600,out:3000},{month:'Feb',in:5200,out:3200},{month:'Mar',in:4800,out:2800},{month:'Apr',in:6000,out:3500},{month:'May',in:5500,out:3300},{month:'Jun',in:6900,out:3900}];
const initialCats=[{name:'Housing',value:38,color:'#4a55db'},{name:'Food & drink',value:24,color:'#8189ed'},{name:'Transport',value:16,color:'#b5baf4'},{name:'Shopping',value:12,color:'#d8daf8'},{name:'Other',value:10,color:'#e9eafb'}];
const cash=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
function App(){
 const [rows,setRows]=useState(()=>{try{return JSON.parse(localStorage.getItem('finwise-transactions'))||seed}catch{return seed}});
 const [dark,setDark]=useState(()=>localStorage.getItem('finwise-theme')==='dark'); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All transactions'); const [sort,setSort]=useState('newest'); const [modal,setModal]=useState(false); const [editing,setEditing]=useState(null); const [menu,setMenu]=useState(false); const [toast,setToast]=useState('');
 const persist=(next)=>{setRows(next);localStorage.setItem('finwise-transactions',JSON.stringify(next))};
 const showToast=(s)=>{setToast(s);setTimeout(()=>setToast(''),2400)};
 const visible=useMemo(()=>rows.filter(r=>(filter==='All transactions'||r.type===filter)&&`${r.name} ${r.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='newest'?b.date.localeCompare(a.date):sort==='oldest'?a.date.localeCompare(b.date):sort==='high'?Math.abs(b.amount)-Math.abs(a.amount):Math.abs(a.amount)-Math.abs(b.amount)),[rows,filter,query,sort]);
 const income=rows.filter(r=>r.amount>0).reduce((s,r)=>s+r.amount,0), expenses=Math.abs(rows.filter(r=>r.amount<0).reduce((s,r)=>s+r.amount,0)), balance=income-expenses;
 function save(e){e.preventDefault();const f=new FormData(e.currentTarget), amount=Number(f.get('amount')), type=f.get('type');const obj={id:editing?.id||Date.now(),name:f.get('name'),category:f.get('category'),date:f.get('date'),amount:type==='Expense'?-Math.abs(amount):Math.abs(amount),type,icon:f.get('name').slice(0,1).toUpperCase(),color:'#e8eaff'};persist(editing?rows.map(r=>r.id===editing.id?obj:r):[obj,...rows]);setModal(false);setEditing(null);showToast(editing?'Transaction updated':'Transaction added')}
 function exportCSV(){const csv=['Name,Category,Date,Type,Amount',...rows.map(r=>[r.name,r.category,r.date,r.type,r.amount].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='finwise-transactions.csv';a.click();URL.revokeObjectURL(a.href);showToast('CSV exported')}
 const current=new Date();
 return <div className={dark?'app dark':'app'}>
  <aside className={`sidebar ${menu?'show':''}`}><div className="brand"><div className="brand-mark"><span></span><span></span><span></span></div><b>finwise</b></div><div className="workspace"><div className="avatar">JD</div><div><b>Jordan Davis</b><small>Personal workspace</small></div><ChevronDown size={15}/></div><div className="nav-label">WORKSPACE</div><nav><a className="active"><LayoutDashboard/>Overview</a><a onClick={()=>document.getElementById('transactions').scrollIntoView({behavior:'smooth'})}><ArrowLeftRight/>Transactions</a><a onClick={()=>document.getElementById('insights').scrollIntoView({behavior:'smooth'})}><ChartNoAxesCombined/>Insights</a><a onClick={()=>showToast('Accounts view is coming soon')}><Wallet/>Accounts</a></nav><div className="nav-label tools-label">PREFERENCES</div><nav><a onClick={()=>{setDark(!dark);localStorage.setItem('finwise-theme',!dark?'dark':'light')}}>{dark?<Sun/>:<Moon/>}{dark?'Light mode':'Dark mode'}</a><a onClick={()=>showToast('Settings saved locally')}><Settings/>Settings</a></nav><div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={17}/></div><b>Need a hand?</b><span>Our help center is here for you.</span><button onClick={()=>showToast('Help center coming soon')}>Visit help center <ArrowUpRight size={14}/></button></div><div className="profile"><div className="avatar">JD</div><div><b>Jordan Davis</b><small>jordan@email.com</small></div><MoreHorizontal size={19}/></div></div></aside>
  <main><header className="topbar"><button className="mobile-menu icon-btn" onClick={()=>setMenu(!menu)}><Menu size={19}/></button><div className="breadcrumbs">Workspace <span>/</span> <b>Overview</b></div><div className="top-actions"><button className="icon-btn" onClick={()=>showToast('You’re all caught up')}><Bell size={18}/><i className="notification-dot"/></button><div className="top-avatar">JD</div></div></header>
  <section className="content"><div className="welcome-row"><div><div className="eyebrow">TUESDAY, JUNE 24, 2025</div><h1>Good morning, Jordan <span>✳</span></h1><p>Here’s what’s happening with your money today.</p></div><button className="primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={17}/> Add transaction</button></div>
  <div className="stats"><article className="stat-card balance-card"><div className="stat-head"><span>Total balance</span><span className="stat-icon blue"><Wallet size={17}/></span></div><div className="stat-value">{cash(balance)}</div><div className="stat-foot"><span className="positive"><ArrowUpRight size={14}/> 12.8%</span><span>vs. last month</span><div className="sparkline"><svg viewBox="0 0 112 36" preserveAspectRatio="none"><path d="M2 29 C12 26 12 21 22 24 S35 17 44 20 S55 15 63 18 S72 9 82 13 S97 8 110 3"/></svg></div></div></article><article className="stat-card"><div className="stat-head"><span>Money in</span><span className="stat-icon green"><ArrowDownRight size={17}/></span></div><div className="stat-value">{cash(income)}</div><div className="stat-foot"><span className="positive"><ArrowUpRight size={14}/> 8.2%</span><span>vs. last month</span></div><div className="mini-bars green-bars">{[22,31,19,43,30,51,35,58,44,68,48,75,58,85,66,92].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></article><article className="stat-card"><div className="stat-head"><span>Money out</span><span className="stat-icon rose"><ArrowUpRight size={17}/></span></div><div className="stat-value">{cash(expenses)}</div><div className="stat-foot"><span className="negative"><ArrowUpRight size={14}/> 3.1%</span><span>vs. last month</span></div><div className="mini-bars rose-bars">{[32,44,26,55,38,48,64,42,71,52,78,60,86,55,69,77].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></article></div>
  <div className="chart-grid"><section className="panel trend-panel"><div className="panel-heading"><div><h2>Cash flow</h2><p>Track your income and expenses over time</p></div><button className="select-btn" onClick={()=>showToast('Showing the last 6 months')}>Last 6 months <ChevronDown size={14}/></button></div><div className="legend"><span><i className="dot income-dot"/>Income</span><span><i className="dot expense-dot"/>Expenses</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:10,right:6,left:0,bottom:0}}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5965e8" stopOpacity={.18}/><stop offset="95%" stopColor="#5965e8" stopOpacity={0}/></linearGradient><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#adb3f6" stopOpacity={.22}/><stop offset="95%" stopColor="#adb3f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eff0f4" strokeDasharray="4 4"/><Tooltip formatter={v=>cash(v)} contentStyle={{borderRadius:12,border:'1px solid #eceef2',fontSize:12}}/><Area type="monotone" dataKey="in" name="Income" stroke="#5661dc" strokeWidth={2.5} fill="url(#incomeFill)"/><Area type="monotone" dataKey="out" name="Expenses" stroke="#aab0ed" strokeWidth={2.5} fill="url(#expenseFill)"/></AreaChart></ResponsiveContainer><div className="chart-months">{trend.map(x=><span key={x.month}>{x.month}</span>)}</div></div></section>
   <section className="panel spending-panel"><div className="panel-heading"><div><h2>Spending breakdown</h2><p>Where your money goes</p></div><button className="dots-btn" onClick={()=>showToast('Spending breakdown options')}><MoreHorizontal size={19}/></button></div><div className="donut-area"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={initialCats} dataKey="value" nameKey="name" innerRadius={63} outerRadius={83} paddingAngle={3} stroke="none">{initialCats.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip formatter={v=>`${v}%`}/></PieChart></ResponsiveContainer><div className="donut-center"><small>Total spent</small><b>{cash(expenses)}</b><span>This month</span></div></div><div className="category-list">{initialCats.slice(0,4).map(c=><div key={c.name}><span><i style={{background:c.color}}/>{c.name}</span><b>{c.value}%</b></div>)}</div></section></div>
  <section className="panel transactions-panel" id="transactions"><div className="panel-heading transaction-title"><div><h2>Recent transactions</h2><p>A closer look at your latest activity</p></div><button className="outline-btn" onClick={exportCSV}><Download size={15}/> Export</button></div><div className="table-tools"><label className="searchbox"><Search size={16}/><input placeholder="Search transactions..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All transactions</option><option>Income</option><option>Expense</option></select><button className="filter-btn" onClick={()=>setSort(sort==='newest'?'oldest':sort==='oldest'?'high':'newest')}><SlidersHorizontal size={15}/> Sort <ChevronDown size={13}/></button><span className="results-count">{visible.length} transactions</span></div><div className="table-scroll"><table><thead><tr><th>TRANSACTION</th><th>CATEGORY</th><th>DATE</th><th>AMOUNT</th><th></th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="transaction-name"><span className="merchant-icon" style={{background:r.color}}>{r.icon}</span><b>{r.name}</b></div></td><td><span className="category-pill">{r.category}</span></td><td className="date-cell">{new Date(r.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</td><td className={r.amount>0?'amount-in':'amount-out'}>{r.amount>0?'+':'−'}{cash(Math.abs(r.amount))}</td><td><div className="row-actions"><button title="Edit" onClick={()=>{setEditing(r);setModal(true)}}><Pencil size={14}/></button><button title="Delete" onClick={()=>{persist(rows.filter(x=>x.id!==r.id));showToast('Transaction deleted')}}><Trash2 size={14}/></button></div></td></tr>)}{visible.length===0&&<tr><td colSpan="5" className="empty">No transactions found. Try another search or add a transaction.</td></tr>}</tbody></table></div><div className="table-footer"><span>Showing <b>{visible.length}</b> of <b>{rows.length}</b> transactions</span><button onClick={()=>setFilter('All transactions')}>View all transactions <ArrowUpRight size={14}/></button></div></section>
  <section className="insights" id="insights"><div className="insights-icon"><Sparkles size={17}/></div><div><b>Your money, in a nutshell</b><p>You spent <strong>{cash(expenses)}</strong> this month. <strong>Food & drink</strong> is your top category, and you’re saving <strong>{cash(Math.max(0,balance))}</strong> of your income.</p></div><button onClick={()=>showToast('More insights coming soon')}>Explore insights <ArrowUpRight size={14}/></button></section><footer>© 2025 Finwise <span>Made for mindful money</span></footer></section></main>
  {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="modal" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setModal(false)}><X size={18}/></button><div className="eyebrow">YOUR MONEY, YOUR WAY</div><h2>{editing?'Edit transaction':'Add transaction'}</h2><p className="modal-sub">Keep your finances up to date.</p><label>Transaction name<input name="name" required placeholder="e.g. Grocery shopping" defaultValue={editing?.name}/></label><div className="form-row"><label>Amount<input name="amount" required type="number" min="0.01" step="0.01" placeholder="0.00" defaultValue={editing?Math.abs(editing.amount):''}/></label><label>Type<select name="type" defaultValue={editing?.type||'Expense'}><option>Expense</option><option>Income</option></select></label></div><div className="form-row"><label>Category<select name="category" defaultValue={editing?.category||'Food & Drink'}>{['Food & Drink','Groceries','Housing','Transport','Entertainment','Shopping','Travel','Software','Salary','Side income','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Date<input name="date" type="date" required defaultValue={editing?.date||new Date().toISOString().slice(0,10)}/></label></div><div className="modal-actions"><button type="button" className="outline-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary"><Check size={16}/>{editing?'Save changes':'Add transaction'}</button></div></form></div>}{toast&&<div className="toast"><Check size={16}/>{toast}</div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);

